### ISSUE TITLE
NPM Repo Out of Date

### ISSUE THREAD

**Issue by stormbard** [mvo5/sha512crypt-node#10]
It seems pulling from [NPMJS](https://www.npmjs.com/package/sha512crypt-node) gives an out of date version to what is in the repository. Are there plans to update NPMJS to the latest or is there another repo it is under?

**Comment by mvo5** [comment]
Thanks, I update the npmjs repo now, please test and let me know if everything is fine.

**Comment by ddolcimascolo** [comment]
@mvo5 For the record, our dependency bot just opened a MR with the upgraded version, build is passing :)

**Comment by ddolcimascolo** [comment]
Good to see some activity in this repo, by the way! Keep up the great work

**Comment by stormbard** [comment]
Confirmed things are as I'd expect after pulling newest version. Gonna close the issue now. Thank you for the great work.

**Comment by mvo5** [comment]
Nice, thanks for testing the update, really appreciate your help here.
