### ISSUE TITLE
Wrong link frontpage

### ISSUE THREAD

**Issue by Vadorequest** [mvo5/sha512crypt-node#4]
Hi.

```
This implements the sha512crypt algorithm as described in http://www.akkadia.org/drepper/SHA-crypt.txt in pure javascript.
```

Wrong link, I guess that should be
https://github.com/mvo5/sha512crypt-node/blob/master/lib/sha512.js

The other link:
http://www.akkadia.org/drepper/SHA-crypt.txt

Is in C language.

**Comment by mvo5** [comment]
Maybe I misunderstand but the link points to the "specification" for the sha512crypt algorithm which is the intended link target. Unless I misunderstand I will close this one.
